### ISSUE TITLE
add option to disable md5 hash compare

### ISSUE THREAD

**Issue by mancdaz** [welbymcroberts/cloudfiles-sync#11]
Add an option into the option file to allow disabling the md5 hash comparison, so that a resume of a sync of a massive number of files (if interrupted for any reason) doesn't take an age to run through the hashes again.

Or, you might just be happy with a filedate comparison.

**Comment by welbymcroberts** [comment]
Added in 0788ce4fa07134fc2b6382686f30f35592c8ecb9
