### ISSUE TITLE
make the parsed directory the 'basename' for uploads

### ISSUE THREAD

**Issue by mancdaz** [welbymcroberts/cloudfiles-sync#2]
Whether supplying a directory contents manually via an issued 'find' or as an argument to the script, always make the directory the base directory for uploads.

eg
find pics/ -type f | python /home/xbmc/cloudfiles-sync/cfsync.py
find /mnt/ter1/pics/ -type f | python /home/xbmc/cloudfiles-sync/cfsync.py

Both of these should result in the following structure in cloudfiles:

pics/filename.1
pics/filename.2
pics/directory1/filename.3

etc

**Comment by welbymcroberts** [comment]
This is now in the v2 branch
