### ISSUE TITLE
allow passing of a file containing a list of objects to sync

### ISSUE THREAD

**Issue by mancdaz** [welbymcroberts/cloudfiles-sync#5]
As well as providing a base directory to sync, allow passing of a file containing a list of files to sync.

**Comment by welbymcroberts** [comment]
As this is currently done via STDIN, I'm going to put this down as not being implemneted, as we can do cat file | cfsync -s

**Comment by mancdaz** [comment]
nah come on, for real?

Leave it open and I'll try and do it as my own little "learn python" project
