### ISSUE TITLE
upload progress indicator

### ISSUE THREAD

**Issue by mancdaz** [welbymcroberts/cloudfiles-sync#7]
as each file is uploaded, show a progress bar.

**Comment by mancdaz** [comment]
and/or a total progress indicator

**Comment by welbymcroberts** [comment]
A simple:
x completed of x (y%)

Has been added as the call back to the load_from_filename call to the cloudfiles api in 
7c986067a815e192456ed5cfa32293d7c6dda3d3

Spliting out total progress indicator to another issue
